<?php ob_start(); ?>
<div>
    <strong>Nom</strong> :
        <a style="font-size:24px;" href="<?php echo $ad->getLink(); ?>"><?php echo $ad->getTitle(); ?></a>
    <br /><br />

    <?php if ($ad->getPrice()) : ?>
        <strong>Prix</strong> : <?php echo number_format($ad->getPrice(), 0, ',', ' '); ?> <?php echo $ad->getCurrency(); ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getDescription()) : ?>
        <strong>Description</strong> : <?php echo $ad->getDescription(); ?> <?php echo $ad->getCurrency(); ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getCategory()) : ?>
        <strong>Catégorie</strong> : <?php echo $ad->getCategory(); ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getCountry()) : ?>
        <strong>Département</strong> : <?php echo $ad->getCountry(); ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getCity()) : ?>
    <strong>Ville</strong> : <a href="https://maps.google.fr/?z=9&q=<?php
        echo htmlspecialchars($ad->getCountry().' '.$ad->getCity());
    ?>" title="Localiser sur Google Map"><?php echo $ad->getCity(); ?></a>
    <?php endif; ?>
    <br />
    <?php if ($siteConfig->getOption("pro_visible")) : ?>
    Annonce de <?php echo $ad->getProfessional()?'professionnel':'particulier.'; ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getUrgent()) : ?>
    <strong style="color: #FF8900;">urgent</strong>
    <?php endif; ?>
    <br />
    <?php $photos = $ad->getPhotos(); ?>
    <?php if (count($photos) > 0) : ?>
        <?php forearch($photos as $photo) : ?>
            <img src="<?php echo $photo; ?>" alt="" style="max-width: 100%; max-height: 600px; overflow:hidden;" />
        <?php endforeach; ?>
    <?php else : ?>
    Pas de photo disponible.
    <?php endif; ?>

    <br />
    <br />
    <?php if ($ad->getDate()) : ?>
    <strong>Publié le <?php echo date("d/m/Y à H:i", $ad->getDate()); ?></strong>
    <?php if (!empty($baseurl) && isset($config) && $config->getOption("allow_backup")) : ?>
    - <a href="<?php echo $baseurl; ?>?mod=annonce&amp;a=backup&amp;aurl=<?php echo rawurlencode($ad->getLink()); ?>"
        target="_blank">SAUVEGARDER L'ANNONCE</a>
    - <a href="<?php echo $baseurl; ?>?mod=mail&amp;a=ignore&amp;aurl=<?php echo rawurlencode($ad->getLink()); ?>"
        target="_blank">NE PLUS RECEVOIR</a>
    <?php endif; ?>
    <br />
    <?php endif; ?>
</div>
<?php
return ob_get_clean();